# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew assembleDebug --stacktrace
#
#    - name: Upload APK
#      uses: actions/upload-artifact@v2
#      with:
#        name: AndroidCICD.apk
#        path: app/build/outputs/apk/debug/app-debug.apk
#
#    - name: Download latest artifact
#      uses: actions/download-artifact@v2
#      with:
#        name: AndroidCICD.apk
#
#    - name: Upload to app center
#      uses: wzieba/AppCenter-Github-Action@v1
#      with:
#        appName: paras.ghasadiya-indianic.com/AndroidCICD
#        token:  ${{ secrets.APP_CENTER_TOKEN }}
#        group: AlphaTesters
#        file: AndroidCICD.apk
#        notifyTesters: true
#        debug: true
  package:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build debug APK
        run: ./gradlew assembleDebug

  deploy:
    needs: [package]
    name: Distribut For Alpha Testing
    runs-on: ubuntu-latest
    steps:
      - name: Upload to app center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: paras.ghasadiya-indianic.com/AndroidCICD
          token:  ${{ secrets.APP_CENTER_TOKEN }}
          group: Collaborators
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: true

      - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: AndroidCICD.zip
            path: app/build/outputs/apk/debug/app-debug.apk